version: '2'
services:
  kraken:
    container_name: 'kraken'
    build: .
    environment:
      PORT: 8000
      ENDPOINT: '/graphql'
      NODE_ENV: 'development'
    volumes:
      - ./:/home/node/app
    ports:
      - 80:8000
