version: '2'
services:
  kraken:
    container_name: 'kraken'
    build: .
    environment:
      PORT: 8000
      ENDPOINT: '/graphql'
      NODE_ENV: 'development'
      SYSTEM_LOG: '/var/log/kraken/system.log'
      PROJECT_NAME: 'kraken'
      CACHE_HOST: 'cache'
      CACHE_PORT: 6379
      CACHE_ENABLED: 1
    volumes:
      - ./:/home/node/app
    ports:
      - 80:8000
      - 9222:9222
    depends_on:
      - cache
  cache:
    image: redis
